apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetflow-api
  namespace: streetflow
  annotations:
    azure.workload.identity/client-id: 69c9ba8d-ba7a-42df-b7cb-bffa82418c05
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: streetflow-worker
  namespace: streetflow
  annotations:
    azure.workload.identity/client-id: 3f840f92-46d6-422d-a6a0-cb11bfdf5d0d
