apiVersion: apps/v1
kind: Deployment
metadata:
  name: streetflow-web
  namespace: streetflow
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: streetflow-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: streetflow-web
    spec:
      containers:
        - name: web
          image: streetflowregistry.azurecr.io/streetflow-web:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
          env:
            - name: API_UPSTREAM
              value: http://streetflow-api.streetflow.svc.cluster.local:3000
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: streetflow-web
  namespace: streetflow
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: streetflow-web
  ports:
    - name: http
      port: 80
      targetPort: http
